### ISSUE TITLE
请问能增加一个上传到tg的功能吗

### ISSUE THREAD

**Issue by garyvalue** [rule-airport/m3u8DL_tgbot#1]
请问能增加一个上传到tg的功能吗

**Comment by garyvalue** [comment]
请问如何上传到有管理权限的频道或者群组呢

**Comment by rule-airport** [comment]
当你是普通用户的时候，运行它，它会上传视频到你的bot里；当你是premium 用户的时候，它会上传视频到 「saved messages」里面。然后你就可以转发到其它频道或者群组了。


> 请问如何上传到有管理权限的频道或者群组呢

**Comment by rule-airport** [comment]
目前仅支持上传视频，没有开发上传其他文件的功能哦。
