### ISSUE TITLE
请问如何使用docker部署

### ISSUE THREAD

**Issue by garyvalue** [rule-airport/m3u8DL_tgbot#2]
修改docker-compose.yml的环境
   
```
 environment:
      - APP_ID=<>
      - APP_HASH=<>
      - TOKEN=<>
      - AUTHORIZED_USERS=<>
```
 若是普通用户使用
 ```
删除 main.py 中的 app_user = Client("app_user") ，app_user.start() ；将 app_user.send_video 修改为 client.send_video。

修改 main.py ：

app = Client("ytdl-main", api_id=api_id, api_hash=api_hash, bot_token=bot_token, ipv6=False)
```
这个步骤还需要执行吗

**Comment by garyvalue** [comment]
```
m3u8dl-bot | sqlite3.OperationalError: unable to open database file
m3u8dl-bot | Traceback (most recent call last):
m3u8dl-bot |   File "/app/main.py", line 58, in <module>
m3u8dl-bot |     app_user.start()
m3u8dl-bot |   File "/usr/local/lib/python3.11/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
m3u8dl-bot |     return loop.run_until_complete(coroutine)
m3u8dl-bot |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
m3u8dl-bot |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
m3u8dl-bot |     return future.result()
m3u8dl-bot |            ^^^^^^^^^^^^^^^
m3u8dl-bot |   File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
m3u8dl-bot |     is_authorized = await self.connect()
m3u8dl-bot |                     ^^^^^^^^^^^^^^^^^^^^
m3u8dl-bot |   File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
m3u8dl-bot |     await self.load_session()
m3u8dl-bot |   File "/usr/local/lib/python3.11/site-packages/pyrogram/client.py", line 616, in load_session
m3u8dl-bot |     await self.storage.open()
m3u8dl-bot |   File "/usr/local/lib/python3.11/site-packages/pyrogram/storage/file_storage.py", line 58, in open
m3u8dl-bot |     self.conn = sqlite3.connect(str(path), timeout=1, check_same_thread=False)
m3u8dl-bot |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
m3u8dl-bot | sqlite3.OperationalError: unable to open database file

```
请问这个报错如何解决呢

**Comment by rule-airport** [comment]
> ```
> 修改docker-compose.yml的环境
> ```
> 
> ```
>  environment:
>       - APP_ID=<>
>       - APP_HASH=<>
>       - TOKEN=<>
>       - AUTHORIZED_USERS=<>
> ```
> 
> 若是普通用户使用
> 
> ```
> 删除 main.py 中的 app_user = Client("app_user") ，app_user.start() ；将 app_user.send_video 修改为 client.send_video。
> 
> 修改 main.py ：
> 
> app = Client("ytdl-main", api_id=api_id, api_hash=api_hash, bot_token=bot_token, ipv6=False)
> ```
> 
> 这个步骤还需要执行吗

当然是需要的

**Comment by rule-airport** [comment]
> ```
> m3u8dl-bot | sqlite3.OperationalError: unable to open database file
> m3u8dl-bot | Traceback (most recent call last):
> m3u8dl-bot |   File "/app/main.py", line 58, in <module>
> m3u8dl-bot |     app_user.start()
> m3u8dl-bot |   File "/usr/local/lib/python3.11/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
> m3u8dl-bot |     return loop.run_until_complete(coroutine)
> m3u8dl-bot |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> m3u8dl-bot |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
> m3u8dl-bot |     return future.result()
> m3u8dl-bot |            ^^^^^^^^^^^^^^^
> m3u8dl-bot |   File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
> m3u8dl-bot |     is_authorized = await self.connect()
> m3u8dl-bot |                     ^^^^^^^^^^^^^^^^^^^^
> m3u8dl-bot |   File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
> m3u8dl-bot |     await self.load_session()
> m3u8dl-bot |   File "/usr/local/lib/python3.11/site-packages/pyrogram/client.py", line 616, in load_session
> m3u8dl-bot |     await self.storage.open()
> m3u8dl-bot |   File "/usr/local/lib/python3.11/site-packages/pyrogram/storage/file_storage.py", line 58, in open
> m3u8dl-bot |     self.conn = sqlite3.connect(str(path), timeout=1, check_same_thread=False)
> m3u8dl-bot |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> m3u8dl-bot | sqlite3.OperationalError: unable to open database file
> ```
> 
> 请问这个报错如何解决呢

session有问题

**Comment by rule-airport** [comment]
哦，对了，普通用户搭建有点儿问题，等晚些时候会修复。

**Comment by rule-airport** [comment]
已经修复好了，根据最新的docker-compose.yml文件创建即可。

**Comment by garyvalue** [comment]
```
m3u8dl-bot | sqlite3.OperationalError: unable to open database file
m3u8dl-bot | INFO:root:PREMIUM: False
m3u8dl-bot | Traceback (most recent call last):
m3u8dl-bot |   File "/app/main.py", line 68, in <module>
m3u8dl-bot |     app.run()
m3u8dl-bot |   File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/utilities/run.py", line 84, in run
m3u8dl-bot |     self.start()
m3u8dl-bot |   File "/usr/local/lib/python3.11/site-packages/pyrogram/sync.py", line 66, in async_to_sync_wrap
m3u8dl-bot |     return loop.run_until_complete(coroutine)
m3u8dl-bot |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
m3u8dl-bot |   File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
m3u8dl-bot |     return future.result()
m3u8dl-bot |            ^^^^^^^^^^^^^^^
m3u8dl-bot |   File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/utilities/start.py", line 58, in start
m3u8dl-bot |     is_authorized = await self.connect()
m3u8dl-bot |                     ^^^^^^^^^^^^^^^^^^^^
m3u8dl-bot |   File "/usr/local/lib/python3.11/site-packages/pyrogram/methods/auth/connect.py", line 40, in connect
m3u8dl-bot |     await self.load_session()
m3u8dl-bot |   File "/usr/local/lib/python3.11/site-packages/pyrogram/client.py", line 616, in load_session
m3u8dl-bot |     await self.storage.open()
m3u8dl-bot |   File "/usr/local/lib/python3.11/site-packages/pyrogram/storage/file_storage.py", line 58, in open
m3u8dl-bot |     self.conn = sqlite3.connect(str(path), timeout=1, check_same_thread=False)
m3u8dl-bot |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
m3u8dl-bot | sqlite3.OperationalError: unable to open database file
```

你好，已经重新clone新的文件，出现如上报错
使用的是普通用户模式，也生成了session
请问是ytdl-main.session的位置放错了吗，目前是在当前文件夹

**Comment by rule-airport** [comment]
你没有使用docker嘛？

**Comment by garyvalue** [comment]
> 你没有使用docker嘛？

是docker

**Comment by rule-airport** [comment]
你自己编译的还是使用的我编译好的？

**Comment by rule-airport** [comment]
我没有使用数据库，你这个问题是数据库权限问题导致的，自行解决。

**Comment by garyvalue** [comment]
> 你自己编译的还是使用的我编译好的？

使用的镜像是povoma4617/m3u8dl-bot:latest

**Comment by rule-airport** [comment]
```
version: '3'
services:
  ytdl:
    container_name: m3u8dl-bot
    image: povoma4617/m3u8dl-bot:latest
    environment:
      - PREMIUM=False
      - AUTHORIZED_USERS=<>
    volumes: 
      - /path/to/ytdl-main.session:/app/ytdl-main.session
    restart: always
```
